// Writes a static, JavaScript-free copy of each page's data-driven content
// (nav, experience, work, stack, projects, certifications) into the HTML, so
// crawlers, link previews and ATS parsers that don't run JavaScript still see
// real roles, dates and credentials instead of {{ … }} templates.
//
// The data comes from each page's own renderVals() and from certs.js, so there
// is one source of truth. The block sits between the prerender markers and is
// removed once the dc runtime has rendered the live page.
//
//   node scripts/prerender.js          rewrite the pages
//   node scripts/prerender.js --check  exit 1 if any page is out of date (CI)
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const START = '<!-- prerender:start (generated by scripts/prerender.js; do not edit) -->';
const END = '<!-- prerender:end -->';
// The static copy is hidden while the runtime boots and removed once React has
// rendered into #dc-root (not merely when #dc-root exists), so a failed render
// falls back to it after five seconds and a late mount still replaces it.
const HEAD_HOOK = '<script>(function(d){var h=d.documentElement,o;h.classList.add(\'js\');function m(){var r=d.getElementById(\'dc-root\');if(!r||!r.firstElementChild)return 0;var p=d.getElementById(\'prerendered\');if(p)p.remove();h.classList.remove(\'js\');o.disconnect();return 1}o=new MutationObserver(m);o.observe(h,{childList:true,subtree:true});setTimeout(function(){if(!m())h.classList.remove(\'js\')},5000)})(document)</script><style>.js #prerendered{display:none}</style>';
const HEAD_HOOK_RE = /^  <script>.*\.js #prerendered\{display:none\}<\/style>\n/m;

function loadCerts() {
  const window = {};
  new Function('window', fs.readFileSync(path.join(ROOT, 'certs.js'), 'utf8'))(window);
  return window;
}

// Evaluates the page's <script data-dc-script> and returns renderVals() for the given state.
function renderVals(html, certs, state = {}) {
  const m = /<script type="text\/x-dc" data-dc-script[^>]*>([\s\S]*?)<\/script>/.exec(html);
  if (!m) throw new Error('no data-dc-script block');
  class DCLogic { constructor() { this.props = {}; } setState() {} }
  const Component = new Function('DCLogic', 'window', m[1] + '\nreturn Component;')(DCLogic, certs);
  const c = new Component();
  c.state = { ...c.state, ...state };
  return c.renderVals();
}

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const link = (href, text) => href ? `<a href="${esc(href)}">${esc(text)}</a>` : esc(text);
const nav = items => `<nav aria-label="Primary"><ul>${items.map(n => `<li>${link(n.href === '#' ? '' : n.href, n.label)}</li>`).join('')}</ul></nav>`;
const certItem = c => `<li>${link(c.href, c.title)} · ${esc(c.issuer)} · ${esc(c.date)}${c.href ? '' : ` · ${esc(c.action)}`}</li>`;

function issuerLine(w) {
  const list = w.JUH_CERT_ISSUERS || [];
  return `${w.JUH_CERTS.length} verified credentials: ` + list.map(([i, n]) => `${esc(i)} ${n}`).join(' · ');
}

const pages = {
  'index.html'(html, w) {
    const v = renderVals(html, w);
    return [
      nav(v.nav),
      '<h2 id="experience">Experience</h2>',
      ...v.jobs.map(j => `<section><h3>${esc(j.role)} · ${esc(j.org)}</h3><p>${esc(j.dates)}</p><ul>${j.points.map(p => `<li>${esc(p)}</li>`).join('')}</ul></section>`),
      '<h2 id="work">Selected work</h2>',
      `<ul>${v.work.map(x => `<li><strong>${esc(x.title)}</strong> (${esc(x.role)}): ${esc(x.desc)} ${esc(x.stack)}</li>`).join('')}</ul>`,
      '<h2 id="stack">Stack</h2>',
      `<ul>${v.stack.map(x => `<li><strong>${esc(x.group)}:</strong> ${esc(x.items)}</li>`).join('')}</ul>`,
      '<h2>Certifications on my résumé</h2>',
      `<ul>${v.certs.map(certItem).join('')}</ul>`,
      `<p>${issuerLine(w)}. ${link('/credentials', 'View all credentials')}</p>`,
      '<h2 id="projects">Projects</h2>',
      `<ul>${[...v.repos, ...v.qeloma].map(r => `<li>${link(r.href, r.name)}: ${esc(r.desc)}</li>`).join('')}</ul>`,
      '<h2 id="contact">Services &amp; contact</h2>',
      `<ul>${v.services.map(x => `<li><strong>${esc(x.t)}:</strong> ${esc(x.d)}</li>`).join('')}</ul>`,
      `<p>Open to Backend Lead, Solutions Architecture and AI Platform roles. ${link('https://gravatar.com/juhbukhari', 'Contact me on Gravatar')}</p>`
    ].join('\n');
  },
  'credentials.html'(html, w) {
    const v = renderVals(html, w, { filter: 'all', expanded: true });
    return [nav(v.nav), '<h1>Certifications &amp; credentials</h1>', `<p>${issuerLine(w)}</p>`, `<ul>${v.certs.map(certItem).join('')}</ul>`].join('\n');
  },
  'case-study.html'(html, w) {
    return nav(renderVals(html, w).nav);
  }
};

function build(html, body) {
  const block = `${START}\n<div id="prerendered">\n${body}\n</div>\n${END}`;
  let out = html.includes(START)
    ? html.replace(new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END), () => block)
    : html.replace(/<body>\n/, () => `<body>\n  ${block}\n`);
  out = out.replace(HEAD_HOOK_RE, '').replace('</head>', () => `  ${HEAD_HOOK}\n</head>`);
  return out;
}

const check = process.argv.includes('--check');
const w = loadCerts();
let stale = 0;
for (const [file, render] of Object.entries(pages)) {
  const p = path.join(ROOT, file);
  const html = fs.readFileSync(p, 'utf8');
  const out = build(html, render(html, w));
  if (out === html) continue;
  if (check) { console.error(`${file} is out of date: run npm run prerender`); stale++; }
  else { fs.writeFileSync(p, out); console.log(`prerendered ${file}`); }
}
process.exit(stale ? 1 : 0);
